codecov:
  notify: {}
  require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_base: false
  require_changes: false
  require_head: true
  show_branch: true
coverage:
  precision: 2
  range:
    - 70.0
    - 100.0
  round: down
  status:
    changes: false
    patch:
      default: {}
    project:
      default: {}
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
